package classifier

import (
	"testing"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if len(cfg.ExcludePatterns) == 0 {
		t.Fatal("expected non-empty ExcludePatterns")
	}
	if len(cfg.GeneratedMarkers) == 0 {
		t.Fatal("expected non-empty GeneratedMarkers")
	}

	// Verify specific defaults exist.
	excludeWant := []string{"vendor/", "third_party/", "testdata/", "node_modules/"}
	for _, want := range excludeWant {
		found := false
		for _, got := range cfg.ExcludePatterns {
			if got == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("ExcludePatterns missing %q", want)
		}
	}

	markerWant := []string{"Code generated", "DO NOT EDIT", "_generated.go", "_gen.go", ".pb.go", "_grpc.go", "_string.go", "zz_generated"}
	for _, want := range markerWant {
		found := false
		for _, got := range cfg.GeneratedMarkers {
			if got == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("GeneratedMarkers missing %q", want)
		}
	}
}

func TestClassifyPath(t *testing.T) {
	cfg := DefaultConfig()

	tests := []struct {
		name        string
		path        string
		wantLang    string
		wantGen     bool
		wantTest    bool
		wantExclude bool
	}{
		{
			name:        "normal production go file",
			path:        "service/web/handler.go",
			wantLang:    "go",
			wantGen:     false,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "test file",
			path:        "service/web/handler_test.go",
			wantLang:    "go",
			wantGen:     false,
			wantTest:    true,
			wantExclude: false,
		},
		{
			name:        "protobuf generated file",
			path:        "pkg/models/user.pb.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "vendor excluded",
			path:        "vendor/github.com/foo/bar.go",
			wantLang:    "go",
			wantGen:     false,
			wantTest:    false,
			wantExclude: true,
		},
		{
			name:        "third_party excluded",
			path:        "third_party/lib/lib.go",
			wantLang:    "go",
			wantGen:     false,
			wantTest:    false,
			wantExclude: true,
		},
		{
			name:        "testdata excluded",
			path:        "testdata/fixtures/test.go",
			wantLang:    "go",
			wantGen:     false,
			wantTest:    false,
			wantExclude: true,
		},
		{
			name:        "generated suffix in filename",
			path:        "pkg/models/user_generated.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "zz_generated prefix in filename",
			path:        "pkg/models/zz_generated_deepcopy.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "grpc generated file",
			path:        "service/web/handler_grpc.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "non-go file",
			path:        "README.md",
			wantLang:    "unknown",
			wantGen:     false,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "node_modules excluded",
			path:        "node_modules/foo/index.js",
			wantLang:    "unknown",
			wantGen:     false,
			wantTest:    false,
			wantExclude: true,
		},
		{
			name:        "gen suffix file",
			path:        "pkg/types/types_gen.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
		{
			name:        "string generated file",
			path:        "pkg/types/color_string.go",
			wantLang:    "go",
			wantGen:     true,
			wantTest:    false,
			wantExclude: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ClassifyPath(tt.path, cfg)

			if got.Language != tt.wantLang {
				t.Errorf("Language = %q, want %q", got.Language, tt.wantLang)
			}
			if got.IsGenerated != tt.wantGen {
				t.Errorf("IsGenerated = %v, want %v", got.IsGenerated, tt.wantGen)
			}
			if got.IsTest != tt.wantTest {
				t.Errorf("IsTest = %v, want %v", got.IsTest, tt.wantTest)
			}
			if got.Excluded != tt.wantExclude {
				t.Errorf("Excluded = %v, want %v", got.Excluded, tt.wantExclude)
			}
		})
	}
}

func TestClassifyContent(t *testing.T) {
	cfg := DefaultConfig()

	tests := []struct {
		name    string
		content string
		wantGen bool
	}{
		{
			name:    "protoc generated header",
			content: "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage models\n",
			wantGen: true,
		},
		{
			name:    "DO NOT EDIT header",
			content: "// DO NOT EDIT. This file was generated by some tool.\npackage generated\n",
			wantGen: true,
		},
		{
			name:    "normal go source",
			content: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n",
			wantGen: false,
		},
		{
			name:    "Code generated in middle of header",
			content: "// This file is Code generated by a tool.\npackage foo\n",
			wantGen: true,
		},
		{
			name:    "empty content",
			content: "",
			wantGen: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ClassifyContent(tt.content, cfg)

			if got.IsGenerated != tt.wantGen {
				t.Errorf("IsGenerated = %v, want %v", got.IsGenerated, tt.wantGen)
			}
		})
	}
}

func TestClassify(t *testing.T) {
	cfg := DefaultConfig()

	t.Run("normal path and normal content", func(t *testing.T) {
		got := Classify("service/web/handler.go", "package web\n\nfunc Handle() {}\n", cfg)

		if got.Language != "go" {
			t.Errorf("Language = %q, want %q", got.Language, "go")
		}
		if got.IsGenerated {
			t.Error("IsGenerated = true, want false")
		}
		if got.IsTest {
			t.Error("IsTest = true, want false")
		}
		if got.Excluded {
			t.Error("Excluded = true, want false")
		}
	})

	t.Run("normal path with generated content", func(t *testing.T) {
		content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage models\n"
		got := Classify("pkg/models/user.go", content, cfg)

		if !got.IsGenerated {
			t.Error("IsGenerated = false, want true (content-based detection)")
		}
	})

	t.Run("excluded path skips content check", func(t *testing.T) {
		content := "package vendor\n\nfunc Foo() {}\n"
		got := Classify("vendor/github.com/foo/bar.go", content, cfg)

		if !got.Excluded {
			t.Error("Excluded = false, want true")
		}
	})

	t.Run("test file with normal content", func(t *testing.T) {
		content := "package web\n\nimport \"testing\"\n\nfunc TestHandle(t *testing.T) {}\n"
		got := Classify("service/web/handler_test.go", content, cfg)

		if !got.IsTest {
			t.Error("IsTest = false, want true")
		}
		if got.IsGenerated {
			t.Error("IsGenerated = true, want false")
		}
	})

	t.Run("generated path with normal content", func(t *testing.T) {
		content := "package models\n\ntype User struct{}\n"
		got := Classify("pkg/models/user.pb.go", content, cfg)

		if !got.IsGenerated {
			t.Error("IsGenerated = false, want true (path-based detection)")
		}
	})
}
